### ISSUE TITLE
Help to install this repo

### ISSUE THREAD

**Issue by mika-nt28** [flaviostutz/freepbx#2]
I can't install this repo in my server
I install with this instruction but I don't connect to http://192.168.0.xxx:8080/
`sudo docker pull flaviostutz/freepbx`
`sudo docker run --name freepbx -d flaviostutz/freepbx`

I see that it is launched on port 80 which is already used
`sudo docker container ls -a`
`CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                                                       NAMES`
`0d77e8a342c2        flaviostutz/freepbx   "/bin/sh -c /run/sta…"   6 minutes ago       Up 5 minutes        80/tcp, 3306/tcp, 4569/tcp, 5060-5061/tcp, 5160-5161/tcp, 10000-20000/udp   freepbx`

And if i change port
sudo docker run --name freepbx -p 8080:80 -d flaviostutz/freepbx
f0964157f08033a7f5deda9c6d653f042ae87aa08f2e7eded690a9c9824a814b
sudo docker container ls -a                                 
 CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                                                                     NAMES
f0964157f080        flaviostutz/freepbx   "/bin/sh -c /run/sta…"   34 seconds ago      Up 23 seconds       3306/tcp, 4569/tcp, 5060-5061/tcp, 5160-5161/tcp, 10000-20000/udp, 0.0.0.0:8080->80/tcp   freepbx

**Comment by flaviostutz** [comment]
The best is to use network mode host because SIP uses a lot of dynamic ports in listen mode and if you configure all those thousand of ports Docker will create a lot of rules (it will even get slower to launch the container). I tried this way before.
Unfortunately the default port on FreePBX is to use port 80 and with network_mode=host you will have conflict. Maybe we could create a way to change this port during startup based on a ENV parameter.

**Comment by mika-nt28** [comment]
Thank you for your help
I do not understand, how I can create with Docker a virtual network
I try as well but it does not work as I want`
sudo docker run --name freepbx --net bridge flaviostutz/freepbx`

**Comment by flaviostutz** [comment]
In plain “docker run”, you have to use “—net host”.
In readme you can see a sample docker-compose.yml that works with network mode host. Please try it.

**Comment by mika-nt28** [comment]
I try your docker compose and it create 3 docker
![image](https://user-images.githubusercontent.com/5501935/51083066-ab768700-1713-11e9-88c5-c8e90e776eae.png)
But I understand the network netplan execution

**Comment by flaviostutz** [comment]
So is it working now?

**Comment by mika-nt28** [comment]
no I don't understand netplan configuration

**Comment by flaviostutz** [comment]
netplan works only on the latest versions of Ubuntu.
The netplan configuration on readme is a sample when you a VoIP provider with a different IP in your network, so that you can reach it with static routing. If this is not your case, just ignore it and use your plain network configuration.

In this case, just run 

docker-compose.yml
```
version: '3.3'
services:
  freepbx:
    image: flaviostutz/freepbx:14.0
    network_mode: host
    restart: always
    volumes:
      - freepbx-backup:/backup
      - freepbx-recordings:/var/spool/asterisk/monitor

volumes:
  freepbx-backup:
  freepbx-recordings:
```

docker-compose up -d

The image is already built in DockerHub, so you don’t need to rebuild it (I removed the build tag after your comments to easy running the container)

**Comment by mika-nt28** [comment]
Ok, I did it right, but my port 80 is already busy.
I Aurrais need to change this port is prossible with the Docker compose

**Comment by aBua-MUC** [comment]
is there meanwhile a solution how the container can be operated as host and port 80 can be changed e.g. to 8080. I have already tried the following variant, but the Freepbx is not accessible under IP:8080.

```
version: '2'
services:
  freepbx-app:
    container_name: freepbx-app
    image: flaviostutz/freepbx
    network_mode: "host"
    volumes:
      - /volume1/docker/asterisk/certs:/certs
      - /volume1/docker/asterisk/data:/data
      - /volume1/docker/asterisk/logs:/var/log
      - /volume1/docker/asterisk/html:/var/www/html

    environment: 
      - HTTP_PORT=8080
      - ZABBIX_HOSTNAME=freepbx-app
      - RTP_START=18000
      - RTP_FINISH=18500
      - DB_EMBEDDED=TRUE
    restart: always
```
